sonar.projectKey=grigoriev_alfred-seedbox-workflow
sonar.organization=grigoriev
sonar.sources=src
sonar.tests=tests
sonar.coverageReportPaths=sonar-coverage.xml
sonar.exclusions=src/update.sh,src/autoupdate.sh
